Tc 960 company details validation
uktrade/export-support pull request #18
Opened 2021-08-31 08:50 UTC by kevincarrogan

2021-09-17 08:24 UTC, Santino-Trade commented on .env.template
> +COMPANIES_HOUSE_TOKEN=<<CHECK_VAULT>>
Is this token the same for dev environment and prod environment? Is the process for a new secret that we only add it to the vault when we need it? (dev has this one at the moment, but not prod)

2021-09-17 08:41 UTC, kevincarrogan commented on .env.template
> +COMPANIES_HOUSE_TOKEN=<<CHECK_VAULT>>
There's no real explicit process when to add it and when not to really, as long as it's added before we deploy it. In this case I've just not done it yet.

2021-09-17 08:43 UTC, Santino-Trade commented on export_support/companies/search.py
> +    while len(items) < DESIRED_NUM_RESULTS:
Using the desired number of 20, does this mean if we return less than 20 results, then we stop updating the list shown to the searcher? E.G, if we search "Wizard" and it returns 19 results, but our company is called "Wizard Void" wouldn't we be quite far down the list even if we typed more of the name in?
Granted, its probably a very rare case, and I guess it would depend on whether it would be worth it to spam the companies-house-api more.

2021-09-17 09:00 UTC, kevincarrogan commented on export_support/companies/search.py
> +    while len(items) < DESIRED_NUM_RESULTS:
This is attempting to always return at least 20 results. It is completely possible that the search returns 1000s but we only ever care about the top 20. If the user types more they should get more accuracy so that's the way of handling it without paging.

The purpose of this is that, by default, the companies house API is returning us 20 results as they return paged data. However, we do additional filtering of these 20 results on our side, so it's highly likely that after filtering we no longer have 20 results, so in this case we keep searching and filtering until we definitely have 20 results on our side, or until the companies house API is no longer returning us anything.

2021-09-17 10:31 UTC, Santino-Trade requested changes
Need to write some unit tests for the new files & code

2021-09-20 10:53 UTC, Santino-Trade approved these changes

2021-09-20 14:09 UTC, merged