Accessibility changes for radio buttons
uktrade/export-support pull request #23
Opened 2021-09-21 13:02 UTC by Santino-Trade

2021-09-21 14:04 UTC, Santino-Trade commented on export_support/core/templates/core/business_details_wizard_step.html
> -                <div class="govuk-radios" data-module="govuk-radios">
Did these radio buttons do something extra that we couldn't use the same way to create them as question page 3 radio buttons?

2021-09-21 14:29 UTC, kevincarrogan requested changes

2021-09-21 14:29 UTC, kevincarrogan commented on export_support/core/templates/core/business_details_wizard_step.html
> -                <div class="govuk-radios" data-module="govuk-radios">
Yes. These did.

The last radio button should display an additional field when selected so you can't just swap this out for the other template.

The bit that's important is the ` data-aria-controls="conditional-type-of-organisation"` (there may be other important bits but that's the one I spotted straight away).

2021-09-21 14:29 UTC, kevincarrogan commented on assets/scss/styles/forms.scss
> +}
Instead of adding this new class use the class `govuk-!-font-weight-regular` instead.

2021-09-21 15:20 UTC, Santino-Trade commented on export_support/core/templates/core/business_details_wizard_step.html
> -                <div class="govuk-radios" data-module="govuk-radios">
Ah, right, yea. Ok, put it back in.

2021-09-22 08:41 UTC, kevincarrogan approved these changes

2021-09-22 08:42 UTC, merged